### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by TerableCoder** [Owyn/field-boss_time#2]
I restarted my game a couple times and then I got this error in the console when I started once.

(node:4460) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning
Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:247:17)
    at process.addListener (events.js:263:10)
    at new field_boss_time (C:\TeraToolbox\mods\field-boss_time-master\index.js:51:10)
    at ModuleManager.load (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:154:35)
    at installedModules.forEach.mod (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:22)
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:118:31)
    at Socket.srvConn.on (C:\TeraToolbox\bin\connectionManager.js:63:47)
    at Socket.emit (events.js:194:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:10)

**Comment by Owyn** [comment]
should be fixed in new version
